checkout/urls.py
from django.urls import path
from checkout import views

app_name='check'
urlpatterns = [
    path('deliverychoices/', views.deliverychoices, name='deliverychoices'), 
    path("basket_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

customuser/urls.py
from django.urls import path

from customuser.views import address_default, address_form, address_list,address_delete, address_update, address_view


app_name='customuser'
urlpatterns = [
    path('address_form', address_form, name='address_form'),        
    path('address_view', address_view, name='address_view'),        
    path('address_list', address_list, name='address_list'),        
    path('address_update/<int:pk>', address_update, name='address_update'),        
    path('address_delete/<int:pk>', address_delete, name='address_delete'),        
    path('address_default/<int:pk>', address_default, name='address_default'),        
    ]

eshops/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', index , name='index'),
    path('messaging/', include('messaging.urls')), 
    path('log/', include('log.urls')), 
    path('check/', include('checkout.urls')), 
    path('basket/', include('basket.urls')), 
    path('customuser/', include('customuser.urls')), 
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

log/urls.py
from django.urls import path
from .views import activate, index, login_user, register, logout_user

app_name='log'
urlpatterns = [
    path('', login_user , name='login'),
    path('register', register , name='register'),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<uidb64>/<token>/', activate , name='activate'),
]

shop/urls.py
from django.conf import settings
from django.urls import path
from .views import add_article, add_product_test,  add_user_article, get_data_cart, calcul, checkout, detail, index, indexajax,   templates, temdetail, add_to_cart
from django.conf.urls.static import static

app_name='shop'
urlpatterns = [
    path('', index, name='index'),
    
    path('<int:pk>', detail , name='detail'),
    path('add/<str:slug>', add_to_cart , name='add_to_cart'),
    path('checkout', checkout , name='checkout'),
    path("create_post", add_article, name="add_article"),
    path("get_data_cart", get_data_cart, name="get_data_cart"),
    
    #test
    path('add_product_test', add_product_test, name='add_product_test'),
    
    path("ajax", indexajax, name="indexajax"),
    path("ww", calcul, name="calcul"),
    
    path("post_creat/", add_user_article, name="add_user_article"),
    path('tem', templates, name='templates'),
    path('temdetail', temdetail, name='temdetail'),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
        ("DD", "Digital Delivery"),
    ]

    delivery_name = models.CharField(
        verbose_name=_("delivery_name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_("list order"), help_text=_("Required"), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

checkout/views.py
import json
from turtle import update
from urllib import response
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from customuser.models import Address

from shop.models import Cart, Order

from .models import DeliveryOptions

#----------- not useful
#----------- not useful
#----------- not useful
#----------- not useful
@login_required
def deliverychoices(request):
    """choix ou delivery"""
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    cart = Cart.objects.filter(user=request.user)
    cart = cart[0]
    return render(request, 'checkout/delivery_choices.html', {'deliveryoptions':deliveryoptions, 'cart':cart})



@login_required
def cart_update_delivery(request):
    cart = Cart.objects.filter(user=request.user)
    cart = cart[0]
    print(cart.total)
    # for verifi post and ajax
    if request.POST.get('action') == 'post':
        # for recup id for integre in the session
        delivery_option = int(request.POST.get('deliveryoption'))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        # for calcul if delivery is payant
        # update_total_price = cart.cart_update_delivery(delivery_type.delivery_price)
        
        delivery_price = int(delivery_type.delivery_price)
        update_total_price = cart.total +int( delivery_price)
        before_price = cart.total
        
        #add in session
        session = request.session
        if 'delivery' not in request.session:
            session['delivery'] = {
                'delivery_id': delivery_type.id,
            }
        else:
            session['delivery']['delivery_id'] = delivery_type.id
            session.modified =True
            
        if 'price' not in request.session:
            session['price'] = {
                'before_price':before_price,
                'delivery_price': delivery_price,
                'total': update_total_price
            }
        else:
            session['price']['total'] = update_total_price
            session['price']['delivery_price'] = delivery_price
            session['price']['before_price'] = before_price
            session.modified =True
        
        response = JsonResponse({'total': update_total_price, 'delivery_price': delivery_price })
        return response
    
    
@login_required
def delivery_address(request):
    session = request.session
    price = session['price']
    
    if 'delivery' not in session:
        messages.success(request, 'Please select delivery options')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    addresses = Address.objects.filter(user=request.user).order_by('-default')
    if addresses:
        if 'address' not in request.session:
                session['address'] = {
                    'address_id': str(addresses[0].id)
                }
        else:
            session['address']['address_id'] = str(addresses[0].id)
            session.modified =True
    
        return render(request, 'checkout/delivery_address.html', {'price':price, 'addresses':addresses})
    return render(request, 'checkout/delivery_address.html', {'price':price, 'addresses':addresses})


@login_required
def payment_selection(request):
    session = request.session
    price = session['price']
    print(session['delivery'])
    if 'address' not in request.session:
        messages.success(request, 'Please select address option')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    
    return render(request, 'checkout/payment_selection.html', {'price':price})



body = ''
@login_required
def payment_complete(request):
    if request.method == 'POST':
        body = json.loads(request.body)
        user = request.user
        user_id = request.user.id

        purchase_units = body['purchase_units'][0]


        total_price =purchase_units['amount']['value']
        total_price = float(total_price)
        name =purchase_units['shipping']['name']['full_name']
        address =purchase_units['shipping']['address']['address_line_1']
        email = body[ 'payer']['email_address']
        city =purchase_units['shipping']['address']['country_code']
        country =purchase_units['shipping']['address']['country_code']
        zipcode =purchase_units['shipping']['address']['postal_code']
        num_order = body['id']

        print( total_price, name, city, zipcode, address, email, num_order)

        
        cart = Cart.objects.get(user=request.user)
        print(cart)
        order = Order.objects.create(
            user = user,
            name =purchase_units['shipping']['name']['full_name'],
            address =purchase_units['shipping']['address']['address_line_1'],
            email = body[ 'payer']['email_address'],
            city =purchase_units['shipping']['address']['country_code'],
            country =purchase_units['shipping']['address']['country_code'],
            zipcode =purchase_units['shipping']['address']['postal_code'],
            total_price =purchase_units['amount']['value'],
            qte = cart.qte,
        #     # achanger au payement
            activate =  True,
            num_order = body['id'],
            )
        # cart.delete()
        order.items.add(cart)
        order.save()
        

        return JsonResponse({'data':'success'})
        # return redirect('payment_successful')
    
    messages.success(request, 'Paypal payment not found')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
    


@login_required
def payment_successful(request):
    cart = Cart.objects.filter(user=request.user)
    # cart.delete()
    return render(request, "checkout/payment_successful.html", {})

checkout/templates/checkout/delivery_address.html
{% extends 'base.html' %}


{% block content %} 





<div class="container">       
    
  <div class="col-12">
    <h1 class="h2">Delivery Address</h1>
  </div>
  <div class="col-12">
    <p>Please select your delivery address</p>
  </div>
  <hr />
</div>
    <div class="container">
          <div class="row g-3">
            {% if addresses|length == 0 %}
            <div class="col-12">There are no delivery addresses, <a href="{% url 'customuser:address_form' %}">add address</a></div>
            {% else %}
            <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
              <div class="d-flex bd-highlight ms-0">
                <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">$ </span><span id="sub_total"
                    class="fw-bold h5">{{ price.before_price }}</span></div>
              </div>
              <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">$ </span><span id="delivery_price"
                    class="fw-bold h5">{{ price.delivery_price}}</span></div>
              </div>
              <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">$ {{ total }}</span><span id="total"
                    class="fw-bold h5">{{ price.total}}</span></div>
              </div>
              <a role="button" href="{% url 'check:payment_selection' %}" class="btn btn-success fw-bold w-100" type="button">Pay Securely</a>
              </div>
    
              <div class="col-md-7 col-lg-8">
              {% for address in addresses %}
              {% if not address.default %}
                <h1 class="h5 pt-4">Other Addresses</h1>
              {% endif %}
              <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
                <div class="row g-0">
                  <div class="col">
                    <div class="card pb-3 rounded-0">
                    <div class="card-header bg-white small text-muted">
                      {% if address.default %}
                      Selected
                      {% endif %}
                      &nbsp;
                    </div>
                    <div class="card-body small pb-1">
                      <p class="card-text m-0 fw-bold">{{address.name}}</p>
                      <p class="card-text m-0">{{address.address}}</p>
                      <p class="card-text m-0">{{address.city}}</p>
                      <p class="card-text m-0">{{address.town_city}}</p>
                      <p class="card-text m-0">{{address.country}}</p>
                      <p class="card-text m-0">{{address.zipcode}}</p>
                      <p class="card-text m-0">Phone number: {{address.phone}}</p>
                      <div class="pt-5">
                        <a href="{% url 'customuser:address_update' address.id %}" class="text-decoration-none">Edit</a>
                        {% if not address.default %}
                    | <a href="{% url 'customuser:address_default' address.id %}" class="text-decoration-none">Select</a>
                    {% endif %}
                  </div>
              </div>
            </div>
            </a>
          </div>
        </div>
      </div>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
       








{% endblock content %}   

{% block js %}

{% endblock js %}

checkout/templates/checkout/delivery_choices.html
{% extends 'base.html' %}


{% block content %} 





<div class="container">       
    
    <div class="col-12">
        <h2>Delivery options</h2>
    </div>
    <div class="col-12">
        <p>Select your delivery options</p>
    </div>
    <hr />
    <div class="container">
 {% if messages %}
        <div class="alert alert-warning" alert-{{ message.tags }} role="alert">
          {% for message in messages  %}
            {{message|safe}}
          {% endfor %}
        </div>
        {% endif %}
          <div class="row g-3">
            {% if deliveryoptions|length == 0 %}
            <div class="col-12">There are no delivery options <a href="{% url 'shop:index' %}">Shop</a></div>
            {% else %}
            <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
              <div class="d-flex bd-highlight ms-0">
                <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">$ </span><span id="sub_total"
                    class="fw-bold h5">{{ cart.total }}</span></div>
              </div>
              <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">$ </span><span id="delivery_price"
                    class="fw-bold h5">{{cart.get_delivery_price}}</span></div>
              </div>
              <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
                <div class="p-2 bd-highlight"><span class="fw-bold h5">$ </span><span id="total"
                    class="fw-bold h5">{{ cart.total }}</span></div>
              </div>
              <a role="button" href="{% url "check:delivery_address" %}" class="btn btn-success fw-bold w-100"
                type="button">Pay Securely</a>
            </div>
            <div class="col-md-7 col-lg-8">
              {% for option in deliveryoptions %}
              <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
                <div class="row g-0">
                  <div class="col-md-2 ps-3 ps-md-4">
                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2"
                      viewBox="0 0 16 16">
                      <path
                        d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                    </svg>
                  </div>
                  <div class="col-md-9 ps-md-1">
                    <div class="card-body p-1">
                      <p class="card-text ps-2 mb-1 pt-1 fw-bold">{{option.delivery_name}}</p>
                      <p class="card-text ps-2 pb-3">Your order should be delivered within {{option.delivery_timeframe}}</p>
                    </div>
                  </div>
                  <div class="col-md-1 ps-md-1">
                    <input class="align-middle h-100" type="radio" name="deliveryOption" id="{{option.id}}"
                      value="{{option.id}}">
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
       








{% endblock content %}   

{% block js %}
<script>
    $('input[type=radio][name=deliveryOption]').on('change', function(e) {
      e.preventDefault();
      $.ajax({
        type: "POST",
        url: '{% url "check:cart_update_delivery" %}',
        data: {
          deliveryoption: $(this).val(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: "post",
        },
        success: function (json) {
          document.getElementById("total").innerHTML = json.total;
          document.getElementById("delivery_price").innerHTML = json.delivery_price;
        },
        error: function (xhr, errmsg, err) {},
      });
      
    });
  </script>
{% endblock js %}

checkout/templates/checkout/payment_selection.html
{% extends 'base.html' %}


{% block content %} 





<div class="container">
  <div class="col-12">
    <h1 class="h2">Secure payment </h1>
  </div>
  <div class="col-12">
    <p>Please select your payment option</p>
  </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
    <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
      <div class="d-flex bd-highlight ms-0">
        <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
            class="fw-bold h5">{{ price.before_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
          class="fw-bold h5">{{ price.delivery_price}}</span></div>
      </div>
      <div class="d-flex bd-highlight">
        <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
        <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
          class="fw-bold h5">{{ price.total}}</span></div>
      </div>
    </div>
    {% csrf_token %}

    <div class="col-md-7 col-lg-8 pe-0 pe-md-5">
      <!-- Replace "test" with your own sandbox Business account app client ID -->
      <script src="https://www.paypal.com/sdk/js?client-id=Aeo7slrixySBdhBZgzMUfLTdwD1ZQOaEuSCPW8Hxv8pRbouwIsgXdaNABmt_sKLypHcWPNf-pxQfa4-c"></script>
    <!-- Set up a container element for the button -->
    <div id="paypal-button-container"></div>

          <script>
            paypal.Buttons({
              // Sets up the transaction when a payment button is clicked
              createOrder: (data, actions) => {
                return actions.order.create({
                  purchase_units: [{
                    amount: {
                      value: '{{ price.total }}' // Can also reference a variable or function
                    }
                  }]
                });
              },
              // Finalize the transaction after payer approval
              onApprove: (data, actions) => {
                return actions.order.capture().then(function(orderData) {
                  // Successful capture! For dev/demo purposes:
                  // console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                  var Capture_result =  orderData;
                  var capture_json = JSON.stringify(orderData, null, 2)
                  console.log(capture_json);
                  // post function
                  send(capture_json);
                  const transaction = orderData.purchase_units[0].payments.captures[0];
                  alert(`Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`);
                  // When ready to go live, remove the alert and show a success message within this page. For example:
                  // const element = document.getElementById('paypal-button-container');
                  // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                  // Or go to another URL:  actions.redirect('thank_you.html');
                  
      
                  location.href ="{% url 'check:payment_successful' %}";
          
      
      
      
                });
              }
            }).render('#paypal-button-container');
      
            // for recup cookies in char
            function getCookie(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
              var cookie = cookies[i].trim();
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
              }
            }
          }
          return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
      
          // for data in post for include in db
          function send(data) {
          const request = new XMLHttpRequest();
          request.open('POST', "{% url 'check:payment_complete' %}");
          request.setRequestHeader('Content-Type', 'application/json');
          request.setRequestHeader('X-CSRFToken', csrftoken);
          request.send(data);
          // result.innerHTML = request.responseText.postData.text;
      }
       
      
          </script>







    <!-- <script>
      function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getCookie('csrftoken');
    
    
    
      function initPayPalButton() {
        paypal.Buttons({
          style: {
            shape: 'rect',
            color: 'gold',
            layout: 'vertical',
            label: 'paypal',
    
          },
        createOrder: function (data, actions) {
            return actions.order.create({
              purchase_units: [{
                "amount": {
                  "currency_code": "USD",
                  "value": '{{price.total}}'
                }
              }]
            });
          },
        onApprove: function (data) {
            var url = "{% url 'check:payment_complete' %}"
            return fetch(url, {
              method: 'POST',
              headers: {
                'content-type': 'application/json',
                'X-CSRFToken': csrftoken,
              },
              body: JSON.stringify({
                orderID: data.orderID
              })
            }).then(function () {
              alert('success');
            console.log();
            })
          },
        }).render('#paypal-button-container');
      }
      initPayPalButton();
    
        </script> -->







    </div>
  </div>
</div>


{% endblock content %}   

{% block js %}


{% endblock js %}

checkout/templates/checkout/payment_successful.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Payment Successful</h1>
  </div>
  <div class="col-12">
    <p>Order Summary</p>
  </div>
  <hr />
  <div class="col-12">
    <p>View all <a href="{% url 'shop:index'%}">All product</a></p>
    <!-- <p>View all <a href="'account:user_orders'---------">orders</a></p> -->
  </div>
</div>


{% endblock %}