basket/urls.py
from django.urls import path

from basket.views import basket_view, basket_add, basket_delete, basket_dimin, basket_page, basket_json
app_name='basket'
urlpatterns = [
    path('', basket_view, name='basket_view' ),
    path('basket_page', basket_page, name='basket_page' ),
    path('basket_add', basket_add, name='basket_add' ),
    path('basket_dimin', basket_dimin, name='basket_dimin' ),
    path('basket_delete', basket_delete, name='basket_delete' ),
    path('basket_json', basket_json, name='basket_json' ),
]

checkout/urls.py
from django.urls import path
from checkout import views

app_name='check'
urlpatterns = [
    path('deliverychoices/', views.deliverychoices, name='deliverychoices'), 
    path("basket_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

eshops/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', index , name='index'),
    path('messaging/', include('messaging.urls')), 
    path('log/', include('log.urls')), 
    path('check/', include('checkout.urls')), 
    path('basket/', include('basket.urls')), 
    path('customuser/', include('customuser.urls')), 
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

log/urls.py
from django.urls import path
from .views import activate, index, login_user, register, logout_user

app_name='log'
urlpatterns = [
    path('', login_user , name='login'),
    path('register', register , name='register'),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<uidb64>/<token>/', activate , name='activate'),
]

shop/urls.py
from django.conf import settings
from django.urls import path
from .views import add_article, add_product_test,  add_user_article, get_data_cart, calcul, checkout, detail, index, indexajax,   templates, temdetail, add_to_cart
from django.conf.urls.static import static

app_name='shop'
urlpatterns = [
    path('', index, name='index'),
    
    path('<int:pk>', detail , name='detail'),
    path('add/<str:slug>', add_to_cart , name='add_to_cart'),
    path('checkout', checkout , name='checkout'),
    path("create_post", add_article, name="add_article"),
    path("get_data_cart", get_data_cart, name="get_data_cart"),
    
    #test
    path('add_product_test', add_product_test, name='add_product_test'),
    
    path("ajax", indexajax, name="indexajax"),
    path("ww", calcul, name="calcul"),
    
    path("post_creat/", add_user_article, name="add_user_article"),
    path('tem', templates, name='templates'),
    path('temdetail', temdetail, name='temdetail'),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

basket/models.py
# this metod is not modal is inclued a basquet in session
# a good is 2 basque 1 in cookies and one in session
from decimal import Decimal
from checkout.models import DeliveryOptions
from eshops import settings
from shop.models import Product

class Basket:
    # a base basket class can herit and overrided
    def __init__(self, request):
        """
        create basquet in request.session
        """
        self.session = request.session
        basket = self.session.get(settings.BASKET_SESSION_ID)
        if settings.BASKET_SESSION_ID not in request.session:
            basket = self.session[settings.BASKET_SESSION_ID] = {}
        self.basket = basket
            
            
    def add(self, product):
        """
        add product in basket (updating the basket in session data
        """
        product_id = str(product.id)
        
        if product_id in self.basket:
            self.basket[product_id]['qty'] +=1
        else:
            self.basket[product_id] = {'name':product.title ,'price': str(product.price), 'qty':1}

        self.save()
        
        
    def dimin(self, product):
        """
        add product in basket (updating the basket in session data
        """
        product_id = str(product.id)
        
        if product_id in self.basket:
            if self.basket[product_id]['qty'] > 1:
                self.basket[product_id]['qty'] -=1
            else:
                self.delete(product=product_id)
        # else:
        #     self.basket[product_id] = {'price': str(product.price), 'qty':1}

        self.save()




    def get_total_price(self):
        newprice = 0.00
        subtotal = sum(Decimal(item["price"]) * item["qty"] for item in self.basket.values())

        if "purchase" in self.session:
            newprice = DeliveryOptions.objects.get(id=self.session["purchase"]["delivery_id"]).delivery_price

        total = subtotal + Decimal(newprice)
        return total

 
    
    def __iter__(self):
        """
        Collect the product_id in the session data to query the database
        and return products
        """
        product_ids = self.basket.keys()
        products = Product.objects.filter(id__in=product_ids)
        basket = self.basket.copy()

        for product in products:
            basket[str(product.id)]["product"] = product

        for item in basket.values():
            item["price"] = Decimal(item["price"])
            item["total_price"] = item["price"] * item["qty"]
            yield item
    
        
    def __len__(self):
        """
        Get the basket data and count the qty of items
        """
        return sum(item["qty"] for item in self.basket.values())
        
        
        
        
    def delete(self, product):
        """
        Delete item from session data
        """
        product_id = str(product)

        if product_id in self.basket:
            del self.basket[product_id]
            self.save()

    def clear(self):
        # Remove basket from session
        del self.session[settings.BASKET_SESSION_ID]
        del self.session["address"]
        del self.session["purchase"]
        self.save()

    def save(self):
        self.session.modified = True

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
        ("DD", "Digital Delivery"),
    ]

    delivery_name = models.CharField(
        verbose_name=_("delivery_name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_("list order"), help_text=_("Required"), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

basket/views.py
import json
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.forms.models import model_to_dict
from basket.models import Basket
# from basket.serializers import BasketSerializer
from shop.models import Product
from django.core import serializers

from django.contrib.auth.decorators import login_required


@login_required
def basket_json(request):
    """json basket"""
    basket = Basket(request)
    data = request.session.get('basket')
    return JsonResponse(data)
@login_required
def basket_view(request):
    return render(request, 'basket/basket_view.html')



@login_required
def basket_page(request):
    basket = Basket(request)
    # good -----request.session['basket']

    print('basket page')

    return render(request, 'basket/checkout.html', {'basket': basket, })

@login_required
def basket_add(request):
    basket = Basket(request)
    print('basket add')
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product = Product.objects.get(id=product_id)
        basket.add(product=product)
        basket.save()
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        basket = request.session['basket']
        return  JsonResponse({'basket': basket, 'qty':basketqty, 'total':baskettotal} )

@login_required
def basket_dimin(request):
    basket = Basket(request)
    print('basket dimin')
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product = Product.objects.get(id=product_id)
        basket.dimin(product=product)
        basket.save()
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        basket = request.session['basket']
        return  JsonResponse({'basket': basket, 'qty':basketqty, 'total':baskettotal} )
    
@login_required   
def basket_delete(request):
    basket = Basket(request)
    print('basket dimin')
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        basket.save()
        basket = request.session['basket']
        return  JsonResponse({'basket': basket} )

checkout/views.py
import json
from turtle import update
from urllib import response
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from customuser.models import Address

from shop.models import Cart, Order

from .models import DeliveryOptions

#----------- not useful
#----------- not useful
#----------- not useful
#----------- not useful
@login_required
def deliverychoices(request):
    """choix ou delivery"""
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    cart = Cart.objects.filter(user=request.user)
    cart = cart[0]
    return render(request, 'checkout/delivery_choices.html', {'deliveryoptions':deliveryoptions, 'cart':cart})



@login_required
def cart_update_delivery(request):
    cart = Cart.objects.filter(user=request.user)
    cart = cart[0]
    print(cart.total)
    # for verifi post and ajax
    if request.POST.get('action') == 'post':
        # for recup id for integre in the session
        delivery_option = int(request.POST.get('deliveryoption'))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        # for calcul if delivery is payant
        # update_total_price = cart.cart_update_delivery(delivery_type.delivery_price)
        
        delivery_price = int(delivery_type.delivery_price)
        update_total_price = cart.total +int( delivery_price)
        before_price = cart.total
        
        #add in session
        session = request.session
        if 'delivery' not in request.session:
            session['delivery'] = {
                'delivery_id': delivery_type.id,
            }
        else:
            session['delivery']['delivery_id'] = delivery_type.id
            session.modified =True
            
        if 'price' not in request.session:
            session['price'] = {
                'before_price':before_price,
                'delivery_price': delivery_price,
                'total': update_total_price
            }
        else:
            session['price']['total'] = update_total_price
            session['price']['delivery_price'] = delivery_price
            session['price']['before_price'] = before_price
            session.modified =True
        
        response = JsonResponse({'total': update_total_price, 'delivery_price': delivery_price })
        return response
    
    
@login_required
def delivery_address(request):
    session = request.session
    price = session['price']
    
    if 'delivery' not in session:
        messages.success(request, 'Please select delivery options')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    addresses = Address.objects.filter(user=request.user).order_by('-default')
    if addresses:
        if 'address' not in request.session:
                session['address'] = {
                    'address_id': str(addresses[0].id)
                }
        else:
            session['address']['address_id'] = str(addresses[0].id)
            session.modified =True
    
        return render(request, 'checkout/delivery_address.html', {'price':price, 'addresses':addresses})
    return render(request, 'checkout/delivery_address.html', {'price':price, 'addresses':addresses})


@login_required
def payment_selection(request):
    session = request.session
    price = session['price']
    print(session['delivery'])
    if 'address' not in request.session:
        messages.success(request, 'Please select address option')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    
    return render(request, 'checkout/payment_selection.html', {'price':price})



body = ''
@login_required
def payment_complete(request):
    if request.method == 'POST':
        body = json.loads(request.body)
        user = request.user
        user_id = request.user.id

        purchase_units = body['purchase_units'][0]


        total_price =purchase_units['amount']['value']
        total_price = float(total_price)
        name =purchase_units['shipping']['name']['full_name']
        address =purchase_units['shipping']['address']['address_line_1']
        email = body[ 'payer']['email_address']
        city =purchase_units['shipping']['address']['country_code']
        country =purchase_units['shipping']['address']['country_code']
        zipcode =purchase_units['shipping']['address']['postal_code']
        num_order = body['id']

        print( total_price, name, city, zipcode, address, email, num_order)

        
        cart = Cart.objects.get(user=request.user)
        print(cart)
        order = Order.objects.create(
            user = user,
            name =purchase_units['shipping']['name']['full_name'],
            address =purchase_units['shipping']['address']['address_line_1'],
            email = body[ 'payer']['email_address'],
            city =purchase_units['shipping']['address']['country_code'],
            country =purchase_units['shipping']['address']['country_code'],
            zipcode =purchase_units['shipping']['address']['postal_code'],
            total_price =purchase_units['amount']['value'],
            qte = cart.qte,
        #     # achanger au payement
            activate =  True,
            num_order = body['id'],
            )
        # cart.delete()
        order.items.add(cart)
        order.save()
        

        return JsonResponse({'data':'success'})
        # return redirect('payment_successful')
    
    messages.success(request, 'Paypal payment not found')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
    


@login_required
def payment_successful(request):
    cart = Cart.objects.filter(user=request.user)
    # cart.delete()
    return render(request, "checkout/payment_successful.html", {})

basket/templates/basket/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}




<div class="container">       
    
  <div class="col-12">
      <h2>Delivery options</h2>
  </div>
  <div class="col-12">
      <p>Select your delivery options</p>
  </div>
  <hr />
  <div class="container">
{% if messages %}
      <div class="alert alert-warning" alert-{{ message.tags }} role="alert">
        {% for message in messages  %}
          {{message|safe}}
        {% endfor %}
      </div>
      {% endif %}
        <div class="row g-3">
          {% if basket|length == 0 %}
          <div class="col-12">There are no delivery options <a href="{% url 'shop:index' %}">Shop</a></div>
          {% else %}
          <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
            <div class="d-flex bd-highlight ms-0">
              <div class="p-2 flex-grow-1 bd-highlight">Quantity: </div>
              <div class="p-2 bd-highlight"><span class="fw-bold h5"></span><span id="basket_total"
                  class="fw-bold h5">{{basket.quantity}}</span></div>
            </div>
            <div class="d-flex bd-highlight">
              <div class="p-2 flex-grow-1 bd-highlight">Total Price:</div>
              <div class="p-2 bd-highlight"><span class="fw-bold h5">$ </span><span id="basket_price"
                  class="fw-bold h5">{{basket.get_delivery_price}}</span></div>
            </div>
            <!-- <div class="d-flex bd-highlight">
              <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
              <div class="p-2 bd-highlight"><span class="fw-bold h5">$ </span><span id="total"
                  class="fw-bold h5">{{ cart.total }}</span></div>
            </div> -->
            <a role="button" href="{% url "check:delivery_address" %}" class="btn btn-success fw-bold w-100"
              type="button">order</a>
          </div>
          <div class="col-md-7 col-lg-8">
            {% for option in basket %}
            <div class="card mb-3 border-1 rounded-0 product-item me-md-4" data-index="{{option.id}}">
              <div class="row g-0">
                <!-- <div class="col-md-2 ps-3 ps-md-4">
                  <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-truck mt-2"
                    viewBox="0 0 16 16">
                    <path
                      d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5v-7zm1.294 7.456A1.999 1.999 0 0 1 4.732 11h5.536a2.01 2.01 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456zM12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12v4zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z" />
                  </svg>
                </div> -->
                <div class="col-md-9 ps-md-1">
                  <div class="card-body p-1">
                    <p class="card-text ps-2 mb-1 pt-1 fw-bold">Product:{{option.name}}</p>
                    <p class="card-text ps-2 pb-3">qty :{{option.qty}} Price: {{option.price}}</p>
                  </div>
                </div>
                <div class="col-md-1 ps-md-1">
                  <button type="button" data-index="4" value="4" class="add-button btn btn-success fw500">Add to
                    basket</button>
                <button type="button" data-index="4"  value="4" class="dimin-button btn btn-warning fw500">dimin to
                    basket</button>
                <button type="button"  data-index="1"  value="1" class="delete-button btn btn-danger fw500">delete 
                    basket</button>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          {% endif %}
        </div>
      </div>
     


      <button type="button" data-index="4" value="4" class="add-button btn btn-success fw500">Add to
        basket</button>
    <button type="button" data-index="4"  value="4" class="dimin-button btn btn-warning fw500">dimin to
        basket</button>
    <button type="button"  data-index="1"  value="1" class="delete-button btn btn-danger fw500">delete 
        basket</button>
    














{% endblock content %}
<div class="container">
    <div class="col-12">
    {% for message in messages %}
        <h5> dfg{{ message}}</h5>{% endfor %}
      <h1 class="h2">Your Basket</h1>
    </div>
    {% if basket|length == 0 %}
    <div class="col-12">
      <p>Your basket is empty <a href="{% url 'shop:index'%}">All product</a></p>
      <!-- <p>View all <a href="'account:user_orders'---------">orders</a></p> -->
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="row g-3">

<div class="container">
        {{ basket.get_total_price}}
        {% for item in basket %}
        {{ item.product}}
        {{ item.price}}
        {{ item.qty}}
        {{ item.total_price}}
        {% endfor %}
      <div class="col-md-4 col-lg-4 order-md-last p-0 order-3">
        <div class="d-flex bd-highlight ms-0">
          <div class="p-2 flex-grow-1 bd-highlight">Sub Total:</div>
          <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="sub_total"
              class="fw-bold h5">{{ price.total}}</span></div>
        </div>
        <!-- <div class="d-flex bd-highlight">
          <div class="p-2 flex-grow-1 bd-highlight">Delivery Cost:</div>
          <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="delivery_price"
            class="fw-bold h5">{{ price.delivery_price}}</span></div>
        </div>
        <div class="d-flex bd-highlight">
          <div class="p-2 flex-grow-1 bd-highlight">Total:</div>
          <div class="p-2 bd-highlight"><span class="fw-bold h5">£</span><span id="total"
            class="fw-bold h5">{{ price.total}}</span></div>
        </div> -->
    </div>
    <a role="button" href="{% url 'check:deliverychoices' %}" class="btn btn-success fw-bold w-100" type="button">Order</a>
    </div>
      </div>
      <div class="col-md-7 col-lg-8">

      </div>
{% endif %}
<div id="basket-qty"></div>
<div id="basket"></div>
<div id="total"></div>
<div id="subtotal"></div>
<!-- <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to -->
<!-- <button type="button" data-index="4" value="4" class="add-button btn btn-success fw500">Add to
    basket</button>
<button type="button" data-index="4"  value="4" class="dimin-button btn btn-warning fw500">dimin to
    basket</button>
<button type="button"  data-index="1"  value="1" class="delete-button btn btn-danger fw500">delete 
    basket</button> -->


</div>







{% block js %}
<script>

  // Add Item
  $(document).on("click", ".add-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        console.log('success add');


        document.getElementById("qty").innerHTML = json.qty;
        document.getElementById("sub_total").innerHTML = json.total;
        // document.getElementById("subtotal").innerHTML = subtotal;
        // console.log(json.basket[1]); // good----------
          for (item in json.basket) {
            console.log(json.basket[item]);
            
          }
        // document.getElementById("basket").innerHTML = json.basket;

      },
      error: function (xhr, errmsg, err) {},
    });
  });


  // Dimin Item
  $(document).on("click", ".dimin-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_dimin" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        console.log('success dimin');
        // $('.product-item[data-index="' + prodid + '"]').remove();

        // if (json.qty == 0) {
        //   total = 0
        //   subtotal = 0
        // } else {
        //   total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
        //   subtotal = json.subtotal
        // }

        // document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        // document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });


  // Delete Item
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        console.log('success delete');
        // $('.product-item[data-index="' + prodid + '"]').remove();

        // if (json.qty == 0) {
        //   total = 0
        //   subtotal = 0
        // } else {
        //   total = (parseFloat(json.subtotal) + 11.50).toFixed(2);
        //   subtotal = json.subtotal
        // }

        // document.getElementById("subtotal").innerHTML = subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty;
        // document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });

</script>
{% endblock js %}