checkout/urls.py
from django.urls import path
from checkout import views

app_name='check'
urlpatterns = [
    path('deliverychoices/', views.deliverychoices, name='deliverychoices'), 
    path("basket_update_delivery/", views.cart_update_delivery, name="cart_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

eshops/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', index , name='index'),
    path('messaging/', include('messaging.urls')), 
    path('log/', include('log.urls')), 
    path('check/', include('checkout.urls')), 
    path('basket/', include('basket.urls')), 
    path('customuser/', include('customuser.urls')), 
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

log/urls.py
from django.urls import path
from .views import activate, index, login_user, register, logout_user

app_name='log'
urlpatterns = [
    path('', login_user , name='login'),
    path('register', register , name='register'),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<uidb64>/<token>/', activate , name='activate'),
]

shop/urls.py
from django.conf import settings
from django.urls import path
from .views import add_article, add_product_test,  add_user_article, get_data_cart, calcul, checkout, detail, index, indexajax,   templates, temdetail, add_to_cart
from django.conf.urls.static import static

app_name='shop'
urlpatterns = [
    path('', index, name='index'),
    
    path('<int:pk>', detail , name='detail'),
    path('add/<str:slug>', add_to_cart , name='add_to_cart'),
    path('checkout', checkout , name='checkout'),
    path("create_post", add_article, name="add_article"),
    path("get_data_cart", get_data_cart, name="get_data_cart"),
    
    #test
    path('add_product_test', add_product_test, name='add_product_test'),
    
    path("ajax", indexajax, name="indexajax"),
    path("ww", calcul, name="calcul"),
    
    path("post_creat/", add_user_article, name="add_user_article"),
    path('tem', templates, name='templates'),
    path('temdetail', temdetail, name='temdetail'),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [
        ("IS", "In Store"),
        ("HD", "Home Delivery"),
        ("DD", "Digital Delivery"),
    ]

    delivery_name = models.CharField(
        verbose_name=_("delivery_name"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_price = models.DecimalField(
        verbose_name=_("delivery price"),
        help_text=_("Maximum 999.99"),
        error_messages={
            "name": {
                "max_length": _("The price must be between 0 and 999.99."),
            },
        },
        max_digits=5,
        decimal_places=2,
    )
    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_("delivery_method"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_("delivery timeframe"),
        help_text=_("Required"),
        max_length=255,
    )
    delivery_window = models.CharField(
        verbose_name=_("delivery window"),
        help_text=_("Required"),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_("list order"), help_text=_("Required"), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Delivery Option")
        verbose_name_plural = _("Delivery Options")

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=_("name"),
        help_text=_("Required"),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _("Payment Selection")
        verbose_name_plural = _("Payment Selections")

    def __str__(self):
        return self.name

shop/models.py
from tkinter.tix import Balloon
from django.utils import timezone
from django.db import models

from eshops.settings import AUTH_USER_MODEL

class Category(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        """for premiere ligne selon date"""
        ordering = ['-date_added']
        
        
class Product(models.Model):
    title = models.CharField(max_length=200)
    price = models.FloatField(default=0)
    description = models.TextField(blank=True)
    slug = models.SlugField(unique=True)
    stock = models.IntegerField(default=0)
    #  etranger key
    Category =models.ForeignKey("Category",  on_delete=models.CASCADE, related_name='category')
    # for image upload 
    # img = models.ImageField
    img = models.CharField(max_length=5000)
    date_added = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        ordering = ['-date_added']
        
    def __str__(self):
        return self.title
    
# ---------create new permition in migrate

    # class Meta:
    #     permissions = (
    #         ('Can_name_permission1', 'description'),
    #         ('Can_name_permission2', 'description'),
    #     )
    
    
#--------------------------create new permission in terminal

# from django.contrib.auth.models import Group, Permission
# from django.contrib.contenttypes.models import ContentType

# ct = ContentType.objects.get_for_model(Product)
# permission = Permission.objects.create(codename='can_do_this', contentype=ct)
    
# ----------------new permission for all model

# class CustomPermissions(models.model):

#     class meta:     
#         # for no database create
#         managed = False 
#         #for not create default permissions
#         default_permissions = () 
#     # new permission

        # permissions = (
        #     ('accept_order', 'can accept order'),
        #     ('reject_order', 'can reject order'),
        # )
        
class Article(models.Model):
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    total = models.FloatField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(null=True, blank=True)
    
    
    def __str__(self):
        return self.product.title

        



class Cart(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    articles = models.ManyToManyField(Article)
    total = models.FloatField(blank=True, null=True)
    qte = models.PositiveIntegerField(blank=True, null=True)
    # class Meta:
    #     ordering = ['-ordered_date']
        
    def __str__(self):
        return self.user.email
    
    def delete(self, *args, **kwargs):
        """save article ordered and clear cart"""
        for article in self.articles.all():
            print(article)
            article.ordered =True
            article.ordered_date = timezone.now()
            article.save()
        self.articles.clear()   
        super().delete(*args, **kwargs)
    
    
    
class Order(models.Model):
    # items = models.CharField(max_length=5000)
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=127)
    address = models.CharField(max_length=127)
    city = models.CharField(max_length=127)
    country = models.CharField(max_length=127)
    zipcode = models.CharField(max_length=127)
    date_added = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    items = models.ManyToManyField(Cart)
    qte = models.PositiveIntegerField(blank=True, null=True)
    total_price = models.FloatField(blank=True, null=True)
    # achanger au payement
    activate = models.BooleanField(default=False)
    num_order = models.CharField(max_length=50, blank=True)
    payment_option = models.CharField(max_length=200, blank=True)
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-date_added']
    
    
    def save(self, *args, **kwargs):
       
    # def save(self, *args, **kwargs):
    #     """save article ordered and clear cart"""
    #     for item in self.items.all():    
    #         toto += item.total
    #     self.total_price = toto
            
        super().save(*args, **kwargs)

checkout/views.py
import json
from turtle import update
from urllib import response
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from customuser.models import Address

from shop.models import Cart, Order

from .models import DeliveryOptions

#----------- not useful
#----------- not useful
#----------- not useful
#----------- not useful
@login_required
def deliverychoices(request):
    """choix ou delivery"""
    deliveryoptions = DeliveryOptions.objects.filter(is_active=True)
    cart = Cart.objects.filter(user=request.user)
    cart = cart[0]
    return render(request, 'checkout/delivery_choices.html', {'deliveryoptions':deliveryoptions, 'cart':cart})



@login_required
def cart_update_delivery(request):
    cart = Cart.objects.filter(user=request.user)
    cart = cart[0]
    print(cart.total)
    # for verifi post and ajax
    if request.POST.get('action') == 'post':
        # for recup id for integre in the session
        delivery_option = int(request.POST.get('deliveryoption'))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        # for calcul if delivery is payant
        # update_total_price = cart.cart_update_delivery(delivery_type.delivery_price)
        
        delivery_price = int(delivery_type.delivery_price)
        update_total_price = cart.total +int( delivery_price)
        before_price = cart.total
        
        #add in session
        session = request.session
        if 'delivery' not in request.session:
            session['delivery'] = {
                'delivery_id': delivery_type.id,
            }
        else:
            session['delivery']['delivery_id'] = delivery_type.id
            session.modified =True
            
        if 'price' not in request.session:
            session['price'] = {
                'before_price':before_price,
                'delivery_price': delivery_price,
                'total': update_total_price
            }
        else:
            session['price']['total'] = update_total_price
            session['price']['delivery_price'] = delivery_price
            session['price']['before_price'] = before_price
            session.modified =True
        
        response = JsonResponse({'total': update_total_price, 'delivery_price': delivery_price })
        return response
    
    
@login_required
def delivery_address(request):
    session = request.session
    price = session['price']
    
    if 'delivery' not in session:
        messages.success(request, 'Please select delivery options')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    addresses = Address.objects.filter(user=request.user).order_by('-default')
    if addresses:
        if 'address' not in request.session:
                session['address'] = {
                    'address_id': str(addresses[0].id)
                }
        else:
            session['address']['address_id'] = str(addresses[0].id)
            session.modified =True
    
        return render(request, 'checkout/delivery_address.html', {'price':price, 'addresses':addresses})
    return render(request, 'checkout/delivery_address.html', {'price':price, 'addresses':addresses})


@login_required
def payment_selection(request):
    session = request.session
    price = session['price']
    print(session['delivery'])
    if 'address' not in request.session:
        messages.success(request, 'Please select address option')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    
    return render(request, 'checkout/payment_selection.html', {'price':price})



body = ''
@login_required
def payment_complete(request):
    if request.method == 'POST':
        body = json.loads(request.body)
        user = request.user
        user_id = request.user.id

        purchase_units = body['purchase_units'][0]


        total_price =purchase_units['amount']['value']
        total_price = float(total_price)
        name =purchase_units['shipping']['name']['full_name']
        address =purchase_units['shipping']['address']['address_line_1']
        email = body[ 'payer']['email_address']
        city =purchase_units['shipping']['address']['country_code']
        country =purchase_units['shipping']['address']['country_code']
        zipcode =purchase_units['shipping']['address']['postal_code']
        num_order = body['id']

        print( total_price, name, city, zipcode, address, email, num_order)

        
        cart = Cart.objects.get(user=request.user)
        print(cart)
        order = Order.objects.create(
            user = user,
            name =purchase_units['shipping']['name']['full_name'],
            address =purchase_units['shipping']['address']['address_line_1'],
            email = body[ 'payer']['email_address'],
            city =purchase_units['shipping']['address']['country_code'],
            country =purchase_units['shipping']['address']['country_code'],
            zipcode =purchase_units['shipping']['address']['postal_code'],
            total_price =purchase_units['amount']['value'],
            qte = cart.qte,
        #     # achanger au payement
            activate =  True,
            num_order = body['id'],
            )
        # cart.delete()
        order.items.add(cart)
        order.save()
        

        return JsonResponse({'data':'success'})
        # return redirect('payment_successful')
    
    messages.success(request, 'Paypal payment not found')
        # meta ... capture de l url (on peut faire ca pour revenir ou faire des condition ca depant d ou on vien)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])
    


@login_required
def payment_successful(request):
    cart = Cart.objects.filter(user=request.user)
    # cart.delete()
    return render(request, "checkout/payment_successful.html", {})

shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico"  />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <meta name="csrf-token" content="{{ csrf_token }}">
        <link rel="shortcut icon" href="#">

        
        
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- <script src="{% static 'detail/js/ajax.js' %}"></script> -->
<!-- Bootstrap core JS-->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="{% static 'detail/js/ajax.js' %}"></script>

        {% block css %}

        {% endblock css %}
        
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">E-shops</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'shop:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:index' %}">All Products</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'shop:index' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                    </form>
                    <!-- <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">
                        Tooltip with HTML
                      </button> -->
                      {% if user.cart %}
                        <button type="button" class="btn btn-outline-dark" data-html="true" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Cart list" id="cart-popo">
                            {% if user.is_authenticated %}
                            <i class="bi-cart-fill me-1"></i>
                            <a href="{% url 'shop:checkout' %}"></a>
                                Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart">{{ user.cart.articles.count }}</span>
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart"></span>
                          </button>
                        {% endif %}

                        
                            <button type="button" class="btn btn-outline-dark mt-auto"  ><a href="{% url 'log:login' %}">Logout</a></button>
                        
                        {% else %}
                        
                            <button type="button" class="btn btn-outline-dark mt-auto" ><a href="{% url 'log:login' %}">Connection</a></button>
                        
                        {% endif %}

                </div>
            </div>
        </nav>

        <section class="py-5">








        
{% block content %} 


{% endblock content %}   

</section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; E-shops Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>-->
        <script src="{% static 'detail/js/ready.js' %}"></script> 


        {% block js %}
        
        {% endblock js %}
    </body>
</html>

shop/templates/base_2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico"  />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <meta name="csrf-token" content="{{ csrf_token }}">
        <link rel="shortcut icon" href="#">

        
        
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- <script src="{% static 'detail/js/ajax.js' %}"></script> -->
<!-- Bootstrap core JS-->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="{% static 'detail/js/ajax.js' %}"></script>

        {% block css %}

        {% endblock css %}
        
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">E-shops</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'shop:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:index' %}">All Products</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'shop:index' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                    </form>
                    <!-- <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">
                        Tooltip with HTML
                      </button> -->
                      {% if user.is_authenticated %}
                      {% if user.cart %}
                        <button type="button" class="btn btn-outline-dark" data-html="true" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Cart list" id="cart-popo">
                            <i class="bi-cart-fill me-1"></i>
                            <a href="{% url 'shop:checkout' %}"></a>
                                Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart">{{ user.cart.articles.count }}</span>
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart"></span>
                          </button>
                        {% endif %}

                        
                            <button type="button" class="btn btn-outline-dark mt-auto"  ><a href="{% url 'log:login' %}">Logout</a></button>
                        
                        {% else %}
                        
                            <button type="button" class="btn btn-outline-dark mt-auto" ><a href="{% url 'log:login' %}">Connection</a></button>
                        
                        {% endif %}

                </div>
            </div>
        </nav>

        <section class="py-5">








        
{% block content %} 


{% endblock content %}   

</section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; E-shops Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>-->
        <script src="{% static 'detail/js/ready.js' %}"></script> 


        {% block js %}
        
        {% endblock js %}
    </body>
</html>

shop/templates/calcul.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Django Ajax</title>
</head>
<body>
<h1>Django Ajax Example</h1>


<!-- Le formulaire -->
<form method="POST">
    {% csrf_token %}
    <label>Opération</label>
    <input type="text" id="a"> + <input type="text" id="b">
    <input type='hidden' id="c" value="aa">
    <input id="ajax-call" type="submit" value="Calculer">
    {% for product in products %}
    {{ product.slug|json_script:'name' }}
    <input id="{{ product.slug }}" value="{{ product.slug }}">{{ product.title }}</input>
    {% endfor %}
</form>
<!-- Nous afficherons le résultat de l'opération ici -->
<p id="ajax"></p>


<script>
document.querySelector("#ajax-call").addEventListener("click", event => {
    event.preventDefault();
    let formData = new FormData();
    let item_id = event.target.id
    console.log(item_id);
    // trransform en string
    formData.append('a', document.querySelector("#a").value);
    formData.append('b', document.querySelector("#b").value);
    var js_variable = JSON.parse(document.getElementById('name').textContent);
    formData.append('c', js_variable);

    let csrfTokenValue = document.querySelector('[name=csrfmiddlewaretoken]').value;

    const request = new Request('{% url "shop:add_user_article" %}', {
        method: 'POST',
        body: formData,
        headers: {'X-CSRFToken': csrfTokenValue}
    });
    
    fetch(request)
        .then(response => response.json())
        .then(result => {
            const resultElement = document.querySelector("#ajax");
            resultElement.innerHTML = result["operation_result"];
        })
})


</script>

</body>
</html>