basket/urls.py
from django.urls import path

from basket.views import basket_view, basket_add, basket_delete, basket_dimin, basket_page, basket_json
app_name='basket'
urlpatterns = [
    path('', basket_view, name='basket_view' ),
    path('basket_page', basket_page, name='basket_page' ),
    path('basket_add', basket_add, name='basket_add' ),
    path('basket_dimin', basket_dimin, name='basket_dimin' ),
    path('basket_delete', basket_delete, name='basket_delete' ),
    path('basket_json', basket_json, name='basket_json' ),
]

eshops/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', index , name='index'),
    path('messaging/', include('messaging.urls')), 
    path('log/', include('log.urls')), 
    path('check/', include('checkout.urls')), 
    path('basket/', include('basket.urls')), 
    path('customuser/', include('customuser.urls')), 
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

log/urls.py
from django.urls import path
from .views import activate, index, login_user, register, logout_user

app_name='log'
urlpatterns = [
    path('', login_user , name='login'),
    path('register', register , name='register'),
    path('login/', login_user , name='login'),
    path('logout/', logout_user , name='logout'),
    path('activate/<uidb64>/<token>/', activate , name='activate'),
]

messaging/urls.py
from django.urls import path

from messaging.views import contact_response_auto, contact_success, contact_view

app_name='messaging'
urlpatterns = [
    path('contact_view', contact_view, name='contact_view'),
    path('contact_response_auto', contact_response_auto, name='contact_response_auto'),
    path('contact_success', contact_success, name='contact_success'),
    ]

shop/urls.py
from django.conf import settings
from django.urls import path
from .views import add_article, add_product_test,  add_user_article, get_data_cart, calcul, checkout, detail, index, indexajax,   templates, temdetail, add_to_cart
from django.conf.urls.static import static

app_name='shop'
urlpatterns = [
    path('', index, name='index'),
    
    path('<int:pk>', detail , name='detail'),
    path('add/<str:slug>', add_to_cart , name='add_to_cart'),
    path('checkout', checkout , name='checkout'),
    path("create_post", add_article, name="add_article"),
    path("get_data_cart", get_data_cart, name="get_data_cart"),
    
    #test
    path('add_product_test', add_product_test, name='add_product_test'),
    
    path("ajax", indexajax, name="indexajax"),
    path("ww", calcul, name="calcul"),
    
    path("post_creat/", add_user_article, name="add_user_article"),
    path('tem', templates, name='templates'),
    path('temdetail', temdetail, name='temdetail'),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <!-- <link rel="icon" type="image/x-icon" href="assets/favicon.ico" /> -->
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <meta name="csrf-token" content="{{ csrf_token }}">
        <!-- <link rel="shortcut icon" href="#"> -->

        
        
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- <script src="{% static 'detail/js/ajax.js' %}"></script> -->
<!-- Bootstrap core JS-->
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="{% static 'detail/js/ajax.js' %}"></script>

        {% block css %}

        {% endblock css %}
        
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!">E-shops</a>
                <a class="navbar-brand" href="/messaging/contact_response_auto">Messaging test</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'shop:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'basket:basket_view' %}">checkout</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'messaging:contact_view' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:index' %}">All Products</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'shop:index' %}">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex">
                    </form>
                    <!-- <button type="button" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<em>Tooltip</em> <u>with</u> <b>HTML</b>">
                        Tooltip with HTML
                      </button> -->
                      {% if user.is_authenticated %}
                      {% if user.cart %}
                      <button type="button" class="btn btn-outline-dark" data-html="true" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Cart list" id="cart-popo">
                            <i class="bi-cart-fill me-1"></i>
                            <a href="{% url 'shop:checkout' %}"></a>
                                Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart-qty"></span>
                          </button>
                        {% endif %}

                        
                            <button type="button" class="btn btn-outline-dark mt-auto"  ><a href="{% url 'log:login' %}">Logout {{ user.firstname }}</a></button>
                        
                        {% else %}
                        
                            <button type="button" class="btn btn-outline-dark mt-auto" ><a href="{% url 'log:login' %}">Connection</a></button>
                        
                        {% endif %}

                </div>
            </div>
        </nav>

        <section class="py-5">








        
{% block content %} 


{% endblock content %}   

</section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; E-shops Website 2022</p></div>
        </footer>
        <!-- Bootstrap core JS
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>-->
        <script src="{% static 'detail/js/ready.js' %}"></script> 

<script>
function basket_fetch(){fetch("{% url 'basket:basket_json' %}", ).then(response =>{
  return response.json();
}).then(data =>{
  let price_total = 0
  // navbar button 'cart'
  document.getElementById("cart-qty").innerHTML = Object.keys(data).length;

  // basket_view 
  // if (document. getElementById('card_product') !== null){     }
  document.getElementById("basket-qty").innerHTML = Object.keys(data).length;
  document.getElementById('card_product').innerHTML = ''
  for(i in data){
      product =  data[i]
      let price = product.price * product.qty
      price_total+= price
    document.getElementById('card_product').innerHTML +=`
    <div class="card">
      <div class="card-body">
        <div class="container">
          <div class="row">
            <button type="button" data-index="${i}"  class="delete-button btn btn-outline-danger btn-sm" >Delete</button>
            <h5 class="col"><br>${product.name}</h5>
            <p class="col">Qty:<br>
              <button type="button" data-index="${i}"   class="dimin-button btn btn-outline-warning btn-sm">-</button>
              <span id='qty-${i}' >${product.qty}</span>
              <button type="button" data-index="${i}"  class="add-button btn btn-outline-success btn-sm" >+</button>
            </p>
            <div class="col">Total Price:<br><span id='price-${i}' >${price}</span></div>
          </div>
        </div>
      </div>
    </div>`
    document.getElementById("basket-price").innerHTML = price_total;} 
  
}).catch( error =>{
  console.log('error basket list');
})}

basket_fetch()


  // Add Item
  $(document).on("click", ".add-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        console.log('success add');
        let qty_prod = json.basket[prodid].qty
        let price_prod =json.basket[prodid].price * qty_prod


        // document.getElementById("basket-qty").innerHTML = json.qty;
        // document.getElementById("basket-price").innerHTML = json.total;
        document.getElementById(`qty-${prodid}`).innerHTML = qty_prod;
        document.getElementById(`price-${prodid}`).innerHTML = price_prod;
        basket_fetch()


      },
      error: function (xhr, errmsg, err) {},
    });
  });



</script>
        {% block js %}
        
        {% endblock js %}
    </body>
</html>